/** Dependency types as used in NeoForge mod metadata file */
enum DependencyType { REQUIRED, OPTIONAL, DISCOURAGED, INCOMPATIBLE }

/** Repositories for external dependencies */
repositories {
    // https://www.cursemaven.com
    maven { url = "https://cursemaven.com"; content { includeGroup "curse.maven" } }
    // https://support.modrinth.com/en/articles/8801191-modrinth-maven
    maven { url = "https://api.modrinth.com/maven"; content { includeGroup "maven.modrinth" } }
}

/** Setup mod-specific dependencies that are hosted on platforms such as CurseForge and Modrinth */
ext.setupExternalDependencies = { ConfigObject mod ->
    mod.dependencies = mod.dependencies.collect { String depModId, ConfigObject dep ->
        dep.modId = depModId
        dep.type = (dep.type ?: "required").toUpperCase() as DependencyType
        dep
    }
    mod.dependencies.forEach { ConfigObject dep -> if(dep.group) {
        String config = switch(dep.type) {
            case DependencyType.REQUIRED -> mod.main.implementationConfigurationName
            case DependencyType.OPTIONAL -> mod.main.compileOnlyConfigurationName
            default -> null
        }
        if(config) dependencies.add(config, [dep.group, dep.modId, dep.versionRange].join(":"))
    } }
}

/** Setup NeoForge with <a href="https://docs.neoforged.net/toolchain/docs/plugins/mdg/">ModDevGradle</a> */
ext.setupNeoForge = { ConfigObject mod -> neoForge {
    mod.loaderVersion = version
    mod.minecraftVersion = minecraftVersion
    mod.neoForgeMod = mods.create(mod.id) { sourceSet mod.main }
    // https://docs.neoforged.net/toolchain/docs/plugins/mdg/#access-transformers
    accessTransformers.from fileTree(mod.resources) { include "META-INF/accesstransformer.cfg" }
    // https://docs.neoforged.net/docs/gettingstarted/modfiles#neoforgemodstoml
    tasks[mod.main.processResourcesTaskName].dependsOn writeNeoForgeMetadataTask(mod)
    // https://docs.neoforged.net/toolchain/docs/plugins/mdg/#runs
    if(!mod.isFarseek) { ["client", "server"].forEach { runType ->
        String runName = runType + mod.name
        runs.register(runName) {
            type = runType
            sourceSet = mod.main
            loadedMods = [mod.neoForgeMod, farseek.neoForgeMod]
            gameDirectory = mkdir("run/$runName")
        }
    } }
} }

/** Task for writing <a href="https://docs.neoforged.net/docs/gettingstarted/modfiles#neoforgemodstoml">neoforge.mods.toml</a> file */
ext.writeNeoForgeMetadataTask = { ConfigObject mod ->
    def tomlLines = { it.collect { key, value -> if(value) "$key = '$value'" else "[[$key]]" } }
    List<String> lines = tomlLines([
        // https://docs.neoforged.net/docs/gettingstarted/modfiles/#non-mod-specific-properties
        license: mod.license,
        // https://docs.neoforged.net/docs/gettingstarted/modfiles/#mod-specific-properties
        mods: null,
        modId: mod.id,
        version: mod.version,
        displayName: mod.displayName,
        description: mod.description,
        logoFile: mod.id + ".logo.png",
        // https://docs.neoforged.net/docs/gettingstarted/modfiles/#mixin-configuration-properties
        mixins: null,
        config: mod.id + ".mixins.json",
    ]) + mod.dependencies.collectMany {
        // https://docs.neoforged.net/docs/gettingstarted/modfiles#dependency-configurations
        ["[[dependencies.${mod.id}]]"] + tomlLines([
            modId: it.modId, type: it.type, versionRange: it.versionRange
        ])
    }
    writeFileTask("writeMetadata" + mod.name, "resources",
        "${mod.generated}/META-INF/neoforge.mods.toml", lines)
}

/** Setup a mod-specific <a href="https://gradleup.com/shadow/custom-tasks">ShadowJar task</a> */
ext.jarTask = { ConfigObject mod ->
    tasks.register(mod.jarTaskName, tasks.shadowJar.class) {
        from mod.main.output
        // bundle Scala libraries in Farseek jar
        if(mod.isFarseek) from mod.main.runtimeClasspath.filter {
            it.name.contains("scala") && it.name.contains("library")
        }.collect { zipTree(it) }
        // https://gradleup.com/shadow/configuration/relocation/#relocating-packages
        relocate "scala", "farseek.scala" // shade scala package
        // https://gradleup.com/shadow/configuration/dependencies
        configurations = [] // don't bundle any other dependencies
        // https://gradleup.com/shadow/configuration/#configuring-output-name
        archiveBaseName   = mod.id
        archiveVersion    = mod.version
        archiveClassifier = mod.loader
    }
}

/** Set up mod-specific <a href="https://modmuss50.github.io/mod-publish-plugin/">Mod Publishing</a> targets */
ext.setupPublishing = { ConfigObject mod -> publishMods {
    // https://modmuss50.github.io/mod-publish-plugin/shared_options/
    var options = publishOptions {
        modLoaders = [mod.loader]
        type = mod.status
        version = mod.version
        file = tasks[mod.jarTaskName].archiveFile
        changelog = file("changes/${mod.id}.md").text + "\n" + file("changes/common.md").text
        displayName = "${mod.titleWithVersion} for ${mod.loader.capitalize()} ${mod.loaderVersion}"
    }.get()
    def addDependencies = { platform ->
        mod.dependencies.forEach { switch(it.type) {
            case DependencyType.REQUIRED     -> platform.requires     it.modId
            case DependencyType.OPTIONAL     -> platform.optional     it.modId
            case DependencyType.INCOMPATIBLE -> platform.incompatible it.modId
            default -> {}
        } }
    }
    // https://modmuss50.github.io/mod-publish-plugin/platforms/github/
    if(mod.repo && mod.branch) github("github" + mod.name) { dryRun = true
        from githubOptions { from options }
        repository = mod.repo
        commitish  = mod.branch
        tagName = "${mod.id}-${mod.version}-${mod.loader}"
        // https://github.com/settings/tokens
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
    }
    // https://modmuss50.github.io/mod-publish-plugin/platforms/curseforge/
    if(mod.curseforgeId) curseforge("curseforge" + mod.name) { dryRun = true
        from curseforgeOptions { from options }
        addDependencies delegate
        projectId = mod.curseforgeId
        minecraftVersions.add mod.minecraftVersion
        // https://legacy.curseforge.com/account/api-tokens
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
    }
    // https://modmuss50.github.io/mod-publish-plugin/platforms/modrinth/
    if(mod.modrinthId) modrinth("modrinth" + mod.name) { dryRun = true
        from modrinthOptions { from options }
        addDependencies delegate
        projectId = mod.modrinthId
        projectDescription = mod.description
        minecraftVersions.add mod.minecraftVersion
        // https://modrinth.com/settings/pats
        accessToken = providers.environmentVariable("MODRINTH_API_KEY")
    }
} }

/** Create mod-specific section for Readme file */
ext.readmeSection = { ConfigObject mod ->
    List<String> lines = ["## " + mod.titleWithVersion]
    if(mod.curseforgeId) {
        // https://support.curseforge.com/en/support/solutions/articles/9000206928-curseforge-badges
        String id = mod.curseforgeId
        String url = "https://www.curseforge.com/projects/$id"
        def badge = { "[![](https://cf.way2muchnoise.eu/${it}.svg)]($url)" }
        lines += [ badge("full_${id}_downloads"), badge("versions/$id") ]
    }
    lines + ["", mod.description, ""]
}
