# https://gradle.org/releases
gradleVersion = 9

# -------------------------------------------------------------------------------------------------
# Gradle options
# -------------------------------------------------------------------------------------------------
# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache = true
# https://docs.gradle.org/current/userguide/build_environment.html#gradle_properties_reference
org.gradle.warning.mode = all
# https://docs.gradle.org/current/userguide/logging.html#stacktraces
org.gradle.logging.stacktrace = all

# -------------------------------------------------------------------------------------------------
# Scala compiler options
# -------------------------------------------------------------------------------------------------
# Docs:   https://docs.scala-lang.org/scala3/guides/migration/options-intro.html
# Source: https://github.com/scala/scala3/blob/main/compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
# Note:   -deprecation and -unchecked are already added by the Scala plugin
compilerOptions = explain, explain-cyclic, feature, source:future, Wall, Werror
# Docs:   https://docs.scala-lang.org/scala3/reference/experimental/index.html
# Source: https://github.com/scala/scala3/blob/main/compiler/src/dotty/tools/dotc/config/Feature.scala
languageFeatures = modularity
