plugins {
    id "scala" // https://docs.gradle.org/current/userguide/scala_plugin.html
    id "com.gradleup.shadow"             version "$shadowVersion" // https://github.com/GradleUp/shadow
    id "net.neoforged.moddev"            version "$modDevVersion" // https://github.com/neoforged/ModDevGradle
    id "me.modmuss50.mod-publish-plugin" version "$modPubVersion" // https://github.com/modmuss50/mod-publish-plugin
}

/**  <a href="https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#basic-usage-for-neoforge-mods">NeoForge extension</a>
@see <a href="https://github.com/neoforged/ModDevGradle/blob/main/src/main/java/net/neoforged/moddevgradle/dsl/NeoForgeExtension.java">source code</a>
*/
neoForge {
    // https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#access-transformers
    AllMods.forEach { mod ->
        File atFile = file(mod.layout.projectDirectory.file("src/main/resources/META-INF/accesstransformer.cfg"))
        if(atFile.exists()) accessTransformers.from atFile
    }
    validateAccessTransformers = true
}

/** Export common NeoForge/Minecraft dependencies to other mods
@see <a href="https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph">Java library configuration graph</a>
*/
configurations {
    scalaLibs
    compileOnlyApi.extendsFrom(configurations.scalaLibs) // exported to other mods
}
dependencies {
    scalaLibs "org.scala-lang:$scalaLibrary:$scalaVersion"
}

/** <a href="https://gradleup.com/shadow/configuration/">Shadow plugin extension</a> */
shadowJar.configurations = [project.configurations.scalaLibs] // https://gradleup.com/shadow/configuration/dependencies

/** Assembles a combined Scala3/Scala2 jar for use in run configurations, since the Java module system disallows package splitting.
@see <a href="https://discord.com/channels/313125603924639766/1185197721477468160/1254510157468143627">discussion on NeoForged discord</a>
*/
tasks.register("scalaLibsJar", Jar) {
    archiveBaseName = "scala-libs"
    from configurations.scalaLibs.collect { zipTree(it) }
}

apply from: buildAnyMod
