name = farseek
title = Farseek
description = A Scala API for Minecraft mods.
authors = delvr
status  = alpha
version = 3.0-alpha.1
curseForgeId = 229708
modrinthId   = TODO

# https://projects.neoforged.net/neoforged/neoforge
# Changes: https://neoforged.net/changelog/
minecraftVersion = 1.21.5
neoForgeVersion  = 21.5.75
dependencies.required.neoforge = [21.5,)

# Docs: https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# Releases: https://parchmentmc.org/docs/getting-started
neoForge.parchment.minecraftVersion = 1.21.5
neoForge.parchment.mappingsVersion  = 2025.06.01

# Releases: https://github.com/scala/scala3/releases
# Warning: avoid "latest.release" as it includes nightly builds
scalaLibrary = scala3-library_3
scalaVersion = 3.7.1
