# Documentation: https://docs.neoforged.net/docs/gettingstarted/modfiles#neoforgemodstoml
# Source: https://github.com/neoforged/FancyModLoader
# MDK example: https://github.com/NeoForgeMDKs/MDK-1.21-ModDevGradle/blob/main/src/main/templates/META-INF/neoforge.mods.toml

# https://docs.neoforged.net/docs/gettingstarted/modfiles#non-mod-specific-properties
modLoader = "javafml"
loaderVersion = "[2,)"
license = "${license}"
#issueTrackerURL = "https://change.me.to.your.issue.tracker.example.invalid/"

# https://docs.neoforged.net/docs/gettingstarted/modfiles#mod-specific-properties
[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${displayName}"
#updateJSONURL = "https://change.me.example.invalid/updates.json"
#displayURL = "https://change.me.to.your.mods.homepage.example.invalid/"
logoFile = "${modId}-logo.png"
#credits = ""
authors = "${authors}"
description = '''${description}'''

# https://docs.neoforged.net/docs/gettingstarted/modfiles/#mixin-configuration-properties
[[mixins]]
config = "${modId}.mixins.json"

# https://docs.neoforged.net/docs/gettingstarted/modfiles#dependency-configurations
${dependencies}
