name: Setup build
description: Setup Java and Gradle
# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax
runs:
  # https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax#runs-for-composite-actions
  using: composite
  steps:
  # https://github.com/madhead/read-java-properties
  - name: Read Java version from Gradle properties
    id  : java-version
    uses: madhead/read-java-properties@4
    with:
      file: gradle/gradle-daemon-jvm.properties
      property: toolchainVersion
  # https://github.com/actions/setup-java
  - name: Setup Java ${{steps.java-version.outputs.value}}
    uses: actions/setup-java@v5
    with:
      java-version: ${{steps.java-version.outputs.value}}
      distribution: microsoft
  # https://github.com/gradle/actions/blob/main/docs/setup-gradle.md
  - name: Setup Gradle
    uses: gradle/actions/setup-gradle@v6
