/** Common build script included by all mods including Farseek. */

//-------------------------------------------------------------------------
// Properties
//-------------------------------------------------------------------------

// https://support.curseforge.com/en/support/solutions/articles/9000206928-curseforge-badges
URL curseForgeModUrl = "$curseForgeUrl/projects/$curseForgeId".toURL()
def curseBadge = { "[![]($curseBadgeUrl/${it}.svg)]($curseForgeModUrl)" }

def prop = { String key, Object defaultValue = null -> properties[key] ?: defaultValue }
def csvProp = { prop(it, "").split(",")*.trim() - "" }

String modId       = project.name
String modVersion  = project.version
String description = project.description
String title       = prop("title")
String authors     = prop("authors")
String license     = prop("license", "MIT")

var modDependencies = {
    String prefix = "dependencies.$it."
    properties.findAll { it.key.startsWith(prefix) }.collectEntries { String key, Object value ->
        [(key.substring(prefix.length())): value] }
}
var requiredDependencies = modDependencies("required")
var optionalDependencies = modDependencies("optional")
ext.readmeSection = ["",
    "## [$title](mods/$modId) $version",
    curseBadge("full_${curseForgeId}_downloads"),
    curseBadge("versions/$curseForgeId"),
    "",
    description,
]

//-------------------------------------------------------------------------
// Compilation
//-------------------------------------------------------------------------
neoForge {
    version = Farseek.neoForgeVersion
    // https://github.com/NeoForged/ModDevGradle?tab=readme-ov-file#access-transformers
    validateAccessTransformers = true
}

/** <a href="https://docs.gradle.org/current/userguide/scala_plugin.html#sec:configure_zinc_compiler">Scala Zinc compiler</a> */
scala.zincVersion = scalaZincVersion

/** <a href="https://docs.gradle.org/current/dsl/org.gradle.api.tasks.scala.ScalaCompile.html">Scala compilation task</a> */
compileScala {
    // https://docs.gradle.org/current/dsl/org.gradle.language.scala.tasks.BaseScalaCompileOptions.html
    scalaCompileOptions.additionalParameters =
        (csvProp("scalaCompilerOptions") + csvProp("scalaLanguageFeatures").collect { "language:experimental.$it" })
        .collect { "-$it".toString() } // toString() prevents ClassCastException in ScalaCompileOptionsConfigurer
}

//-------------------------------------------------------------------------
// Resource processing
//-------------------------------------------------------------------------
var dependenciesToml = [requiredDependencies, optionalDependencies].collectMany {
    it.collectMany { String depModId, String versionRange -> [
        "[[dependencies.$modId]]",
        "modId = '$depModId'",
        "versionRange = '$versionRange'",
        "mandatory = ${it == requiredDependencies}",
        "ordering = 'AFTER'"
    ]}
}.join("\n")
var modProperties = [
    modId: modId,
    version: modVersion,
    displayName: title,
    description: description,
    authors: authors,
    license: license,
    dependencies: dependenciesToml
]
// https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
tasks.register("generateResources", ProcessResources) {
    inputs.properties modProperties
    expand modProperties
    from parent.layout.projectDirectory.dir(".resources")
    into layout.buildDirectory.dir("generated/resources")
}
sourceSets.main.resources.srcDir generateResources
neoForge.ideSyncTask generateResources
clean { delete "out" }

//-------------------------------------------------------------------------
// Assembly/Publishing
//-------------------------------------------------------------------------
var modLoader = "neoforge"
// Regular jar is replaced by shadowed jar
jar {
    enabled = false
    dependsOn shadowJar
}
/** <a href="https://gradleup.com/shadow/configuration/">Shadow plugin extension</a> */
shadowJar {
    // https://gradleup.com/shadow/configuration/relocation/#relocating-packages
    relocate "scala", "farseek.scala"
    // https://docs.neoforged.net/docs/gettingstarted/versioning#including-the-mod-loader
    archiveClassifier = "${modLoader}-${Farseek.neoForgeVersion}"
}
