# -------------------------------------------------------------------------------------------------
# Project settings
# -------------------------------------------------------------------------------------------------

# https://docs.neoforged.net/docs/gettingstarted/modfiles/#the-group-id
group = farseek
# Readme properties
title = Farseek Mods
description = A monorepo for the Farseek library and the Minecraft mods that use it.
# Readme badge URLs
curseForgeUrl = https://www.curseforge.com
curseBadgeUrl = https://cf.way2muchnoise.eu

# -------------------------------------------------------------------------------------------------
# Plugin versions
# -------------------------------------------------------------------------------------------------

# https://projects.neoforged.net/neoforged/moddevgradle
modDevVersion = latest.release
# https://github.com/modmuss50/mod-publish-plugin
modPubVersion = latest.release
# https://github.com/GradleUp/shadow
shadowVersion = latest.release

# -------------------------------------------------------------------------------------------------
# Scala compilation settings
# -------------------------------------------------------------------------------------------------

# Docs:     https://docs.gradle.org/current/userguide/scala_plugin.html#sec:configure_zinc_compiler
# Releases: https://github.com/sbt/zinc/releases, https://mvnrepository.com/artifact/org.scala-sbt/zinc
scalaZincVersion = latest.release

# Docs:   https://docs.scala-lang.org/scala3/guides/migration/options-intro.html
# Source: https://github.com/scala/scala3/blob/main/compiler/src/dotty/tools/dotc/config/ScalaSettings.scala
# Note:   -deprecation and -unchecked are already added by the Scala plugin
scalaCompilerOptions = explain, explain-cyclic, feature, source:future, Wall, Werror

# Docs:   https://scala-lang.org/api/3.6.3/docs/docs/reference/experimental/index.html
# Source: https://github.com/scala/scala3/blob/main/compiler/src/dotty/tools/dotc/config/Feature.scala
#         https://github.com/scala/scala3/blob/main/library/src/scala/runtime/stdLibPatches/language.scala
scalaLanguageFeatures = into, modularity, namedTypeArguments
