// HOCON syntax: https://github.com/lightbend/config/blob/main/HOCON.md

project {
  name       : farseek-mods
  description: "A monorepo for the Farseek library and the Minecraft mods that use it."
  license    : "MIT"
  licensePage: "https://opensource.org/license/mit"
  homepage   : "https://github.com/delvr/Farseek-Mods"
  issuesPage : ${project.homepage}"/issues"
  workflows  : ${project.homepage}"/actions/workflows"
  badges     : ["githubWorkflow:push", "githubWorkflow:publish"]
}
mod-defaults {
  authors    : [delvr]
  license    : ${project.license}
  homepage   : ${project.homepage}
  issuesPage : ${project.issuesPage}
  licensePage: ${project.licensePage}
//TODO devClassifier: dev // expected by mcPublish plugin defaults
}
mods {
  farseek: ${mod-defaults} {
    description : "A Scala API for Minecraft mods."
    dependencies: [neoforge, scala]
    platformIds : {curseforge: "229708"} //, modrinth: "SlKHbCyh"}
  }
  repose: ${mod-defaults} {
    description : "This mod allows players and mobs to smoothly walk up and down hills without jumping."
    dependencies: [farseek]
    platformIds : {curseforge: "220524"} //, modrinth: "vgIu0FCG"}
  }
  streams: ${mod-defaults} {
    description : "This mod introduces real flowing rivers, with a true current, to your Minecraft worlds."
    dependencies: [farseek]
    platformIds : {curseforge: "229769"} //, modrinth: "lkKoniya"}
  }
}
dependencies {
  farseek: ${mods.farseek} {
    minVersion: "3.0.0-beta.0"
    maxVersion: "3.0.0-beta.0"
  }
  neoforge {
    displayName: "NeoForge"
    homepage   : "https://neoforged.net"
    mavenGroup : net.neoforged
    mavenName  : neoforge
    // https://neoforged.net/changelog
    minVersion : "26.2.0.57"
    maxVersion : "26.2.999"
  }
  scala {
    homepage   : "https://github.com/scala/scala3"
    mavenGroup : org.scala-lang
    mavenName  : scala-library
    type       : embedded
    // https://github.com/scala/scala3/releases
    minVersion : "3.9.0-RC1"
    maxVersion : "3.9.999"
  }
}
platforms {
  curseforge {
    displayName: "CurseForge"
    mavenUri   : "https://cursemaven.com"
    mavenGroup : curse.maven
    homepage   : "https://www.curseforge.com/projects/PLACEHOLDER"
    badgeUri   : ${badgeHosts.devins}"/available/curseforge_vector.svg"
  }
  modrinth {
    mavenUri   : "https://api.modrinth.com/maven"
    mavenGroup : maven.modrinth
    homepage   : "https://modrinth.com/mod/PLACEHOLDER"
    badgeUri   : ${badgeHosts.devins}"/available/modrinth_vector.svg"
  }
}
authors {
  delvr {
    displayName: "delvr"
    homepage   : "https://linktr.ee/delvr"
    description: "Visit me on Linktree: "${authors.delvr.homepage}
    badges: ["githubUser:delvr", "youtubeUser:delvr", "kofiUser:delvr"]
  }
}
badges: ${dependencies} ${platforms} {
  // https://docs.github.com/en/actions/how-tos/monitor-workflows/add-a-status-badge
  githubWorkflow {
    homepage: ${project.workflows}"/PLACEHOLDER.yml"
    badgeUri: ${project.workflows}"/PLACEHOLDER.yml/badge.svg"
  }
  githubUser {
    homepage: "https://github.com/PLACEHOLDER"
    badgeUri: ${badgeHosts.devins}"/social/github-singular_vector.svg"
  }
  youtubeUser {
    homepage: "https://www.youtube.com/@PLACEHOLDER"
    badgeUri: ${badgeHosts.devins}"/social/youtube-singular_vector.svg"
  }
  kofiUser {
    homepage: "https://ko-fi.com/PLACEHOLDER"
    badgeUri: ${badgeHosts.devins}"/donate/kofi-singular_vector.svg"
  }
}
badgeHosts {
  // https://intergrav.github.io/devins-badges-docs/badges
  devins: "https://cdn.jsdelivr.net/npm/@intergrav/devins-badges@3/assets/cozy"
}
