name: Publish mod
permissions:
  contents: read
on:
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs:
      mod-id:
        description: Mod ID
        required: true
        type    : choice
        options : [farseek, streams, repose]
      # https://github.com/release-flow/keep-a-changelog-action/blob/main/docs/bump.md#action-inputs
      release-type:
        description: Release type
        required: true
        type    : choice
        options : [major, premajor, minor, preminor, patch, prepatch, prerelease, release]
      # https://github.com/npm/node-semver?tab=readme-ov-file#prerelease-identifiers
      prerelease-id:
        description: Prerelease identifier
        required: true
        type    : choice
        options : ['', alpha, beta]
        default :  ''
run-name: Publish ${{inputs.mod-id}} ${{inputs.release-type}} ${{inputs.prerelease-id}}
jobs:
  publish:
    runs-on: ubuntu-latest # git-auto-commit-action requires a Unix system
    environment: releases
    permissions:
      contents: write
    steps:
    # https://github.com/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        # For bypassing PR requirement on branch when using git-auto-commit-action
        ssh-key: ${{secrets.DEPLOY_KEY}}
        # https://github.com/stefanzweifel/git-auto-commit-action#action-does-not-push-commit-to-repository-authentication-issue
        persist-credentials: true
    # https://github.com/release-flow/keep-a-changelog-action/blob/main/docs/bump.md
    - name: Update mod changelog
      id  : changelog
      uses: release-flow/keep-a-changelog-action@v3
      with:
        command: bump
        tag-prefix: ${{inputs.mod-id}}-
        version   : ${{inputs.release-type}}
        preid     : ${{inputs.prerelease-id}}
        changelog : changelogs/${{inputs.mod-id}}.md
        keep-unreleased-section    : true
        fail-on-empty-release-notes: true
    # Setup build
    - name: Setup build
      uses: ./.github/actions/setup-build
    # Build mod using new version
    - name: Build ${{inputs.mod-id}}-${{steps.changelog.outputs.version}}
      id  : build
      run : ./gradlew buildToPublish -Dmods.${{inputs.mod-id}}.version=${{steps.changelog.outputs.version}}
    # https://github.com/stefanzweifel/git-auto-commit-action
    - name: Commit changes with release tag
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message : Prepare release ${{inputs.mod-id}}-${{steps.changelog.outputs.version}}
        tagging_message:         Release ${{inputs.mod-id}}-${{steps.changelog.outputs.version}}
        tag_name       :                 ${{inputs.mod-id}}-${{steps.changelog.outputs.version}}
    # https://github.com/Kira-NT/mc-publish
    - name: Publish ${{steps.build.outputs.name}}
      uses: Kira-NT/mc-publish@v3
      with:
        name      : ${{steps.build.outputs.name}}
        version   : ${{steps.changelog.outputs.version}}
        changelog : ${{steps.changelog.outputs.release-notes}}
        github-commitish: ${{github.ref_name}}
        github-tag      : ${{inputs.mod-id}}-${{steps.changelog.outputs.version}}
        curseforge-token: ${{secrets.CURSEFORGE_TOKEN}}
        modrinth-token  : ${{secrets.MODRINTH_TOKEN}}
        github-token    : ${{secrets.GITHUB_TOKEN}}
