name: Build and test mods
permissions:
  contents: read
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Setup build
      uses: ./.github/actions/setup-build
    - name: Generate testing matrix
      id  : testingMatrix
      run : ./gradlew testingMatrix -DoutputFile=$GITHUB_OUTPUT
    outputs:
      args: ${{steps.testingMatrix.outputs.args}}
  build-and-test:
    needs: setup
    # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations
    strategy:
      # https://docs.github.com/en/actions/reference/workflows-and-actions/expressions#fromjson
      matrix:
        arg: ${{fromJSON(needs.setup.outputs.args)}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Setup build
      uses: ./.github/actions/setup-build
    - name: Build and test with ${{matrix.arg || 'latest dependencies'}}
      run : ./gradlew build ${{matrix.arg}}
