name: Republish mod to CurseForge
permissions:
  contents: read
on:
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs:
      mod-id:
        description: Mod ID
        required: true
        type    : choice
        options : [farseek, streams, repose]
run-name: Republish ${{inputs.mod-id}} to CurseForge
jobs:
  publish: # name expected in build.gradle
    runs-on: ubuntu-latest # git-auto-commit-action requires a Unix system
    environment: releases
    steps:
    # https://github.com/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v7
    # https://github.com/release-flow/keep-a-changelog-action/blob/main/docs/query.md
    - name: Get mod version from changelog
      id  : changelog
      uses: release-flow/keep-a-changelog-action@v3
      with:
        command: query
        version: latest
        changelog: changelogs/${{inputs.mod-id}}.md
    # Setup build
    - name: Setup build
      uses: ./.github/actions/setup-build
    # Build mod using new version
    - name: Build ${{inputs.mod-id}}-${{steps.changelog.outputs.version}}
      run : ./gradlew build -Dmods.${{inputs.mod-id}}.version=${{steps.changelog.outputs.version}}
    # https://github.com/Kira-NT/mc-publish
    - name: Publish mod
      uses: Kira-NT/mc-publish@v3
      with:
        version   : ${{steps.changelog.outputs.version}}
        changelog : ${{steps.changelog.outputs.release-notes}}
        github-tag: ${{inputs.mod-id}}-${{steps.changelog.outputs.version}}
        github-commitish: ${{github.ref_name}}
        curseforge-token: ${{secrets.CURSEFORGE_TOKEN}}
